"""Notebook assembly — converts LLM cell output to a valid .ipynb file."""
import logging
from typing import Any

import nbformat

from app.sanitizer import NOTEBOOK_DISCLAIMER, generate_warning_cell, scan_code_cell

logger = logging.getLogger(__name__)


def build_notebook(
    cells: list[dict[str, str]],
    paper_meta: dict[str, Any],
) -> bytes:
    """Build a valid .ipynb notebook from LLM-generated cells.

    Args:
        cells: List of dicts with cell_type ("markdown"|"code") and source keys.
        paper_meta: Dict with title and authors from the paper.

    Returns:
        UTF-8 encoded bytes of the .ipynb JSON file.
    """
    nb = nbformat.v4.new_notebook()

    # ── Notebook-level metadata ──────────────────────────
    nb.metadata.kernelspec = {
        "name": "python3",
        "display_name": "Python 3",
        "language": "python",
    }
    nb.metadata.language_info = {
        "name": "python",
        "version": "3.10",
        "mimetype": "text/x-python",
        "file_extension": ".py",
    }
    nb.metadata.colab = {
        "provenance": [],
        "name": f"{paper_meta.get('title', 'Paper')} — Implementation Notebook",
        "collapsed_sections": [],
    }
    nb.metadata.accelerator = "GPU"

    # ── Header cell ──────────────────────────────────────
    title = paper_meta.get("title", "Research Paper")
    authors = paper_meta.get("authors", "")
    header_source = (
        f"# {title}\n\n"
        f"**Authors:** {authors}\n\n"
        "---\n\n"
        "*This notebook was automatically generated by "
        "[Paper-to-Notebook](https://github.com/paper-to-notebook) — "
        "an AI-powered research paper implementation tool.*\n\n"
        "**How to use:** Run all cells sequentially. "
        "GPU runtime is recommended for faster execution.\n\n"
        "---"
    )
    nb.cells.append(nbformat.v4.new_markdown_cell(header_source))

    # ── Disclaimer cell (SEC-005) ────────────────────────
    nb.cells.append(nbformat.v4.new_markdown_cell(NOTEBOOK_DISCLAIMER))

    # ── Setup cell (pip installs) ─────────────────────────
    # Collect packages mentioned in code cells
    packages = _detect_packages(cells)
    if packages:
        install_lines = " ".join(sorted(packages))
        setup_source = f"# Environment setup — install required packages\n!pip install -q {install_lines}"
    else:
        setup_source = "# Environment setup\n!pip install -q numpy matplotlib torch"
    nb.cells.append(nbformat.v4.new_code_cell(setup_source))

    # ── LLM-generated cells ──────────────────────────────
    for cell in cells:
        cell_type = cell.get("cell_type", "")
        source = cell.get("source", "")

        # Skip empty cells
        if not source.strip():
            continue

        if cell_type == "markdown":
            nb.cells.append(nbformat.v4.new_markdown_cell(source))
        elif cell_type == "code":
            # Scan code for dangerous patterns (SEC-005)
            scan = scan_code_cell(source)
            if scan.is_flagged:
                logger.warning("Flagged code cell: %s", scan.reasons)
                warning_md = generate_warning_cell(scan.reasons)
                nb.cells.append(nbformat.v4.new_markdown_cell(warning_md))
            nb.cells.append(nbformat.v4.new_code_cell(source))
        else:
            logger.warning("Skipping cell with unknown type: %s", cell_type)

    # ── Validate ─────────────────────────────────────────
    nbformat.validate(nb)

    return nbformat.writes(nb).encode("utf-8")


def _detect_packages(cells: list[dict[str, str]]) -> set[str]:
    """Detect Python packages from import statements in code cells."""
    common_packages = {
        "numpy": "numpy",
        "np": "numpy",
        "torch": "torch",
        "tensorflow": "tensorflow",
        "tf": "tensorflow",
        "matplotlib": "matplotlib",
        "plt": "matplotlib",
        "plotly": "plotly",
        "scipy": "scipy",
        "sklearn": "scikit-learn",
        "pandas": "pandas",
        "pd": "pandas",
        "seaborn": "seaborn",
        "sns": "seaborn",
        "transformers": "transformers",
        "jax": "jax",
        "tqdm": "tqdm",
    }

    found: set[str] = set()
    for cell in cells:
        if cell.get("cell_type") != "code":
            continue
        source = cell.get("source", "")
        for alias, package in common_packages.items():
            if f"import {alias}" in source or f"from {alias}" in source:
                found.add(package)

    return found
